# IMPORT LIBRARY

In [2]:
import tensorflow as tf

# Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [4]:
random_tensor = tf.random.normal([5,5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-2.2673783 ,  0.5947161 , -1.0716033 ,  0.12887874, -1.6241169 ],
       [-1.1072237 , -0.06681984, -0.96344835,  0.09568334,  0.5920073 ],
       [-1.49651   , -1.0106903 , -1.8050754 ,  1.1555853 ,  0.323326  ],
       [-1.535353  ,  0.49010277, -0.81873935, -2.491196  , -0.24670306],
       [-0.44303843, -1.5578623 ,  0.14702404, -0.5202944 ,  1.2270253 ]],
      dtype=float32)>

# Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [5]:
list = [[2, 3, 5, 7, 11],
       [13, 17, 19, 23, 29],
       [31, 37, 41, 43, 47],
       [ 53, 59, 61, 67, 71],
       [ 73, 79, 83, 89, 97]]
prime_tensor = tf.convert_to_tensor(list, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

# Tampilkan dimensi dari kedua variable tersebut

In [7]:
print ("Dimensi Dari Variabel random_tensor : ", random_tensor.shape)
print ("Dimensi Dari Variabel random_tensor : ", prime_tensor.shape)

Dimensi Dari Variabel random_tensor :  (5, 5)
Dimensi Dari Variabel random_tensor :  (5, 5)


# Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

#### Penjumlahan

In [12]:
tf.add(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.26737833,  3.594716  ,  3.9283967 ,  7.1288786 ,  9.375883  ],
       [11.8927765 , 16.93318   , 18.036552  , 23.095684  , 29.592007  ],
       [29.50349   , 35.98931   , 39.194923  , 44.155586  , 47.323326  ],
       [51.464645  , 59.490105  , 60.18126   , 64.508804  , 70.753296  ],
       [72.55696   , 77.44214   , 83.147026  , 88.479706  , 98.22703   ]],
      dtype=float32)>

#### Pengurangan

In [14]:
tf.subtract(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -4.2673783,  -2.405284 ,  -6.0716033,  -6.8711214, -12.624117 ],
       [-14.1072235, -17.06682  , -19.963448 , -22.904316 , -28.407993 ],
       [-32.49651  , -38.01069  , -42.805077 , -41.844414 , -46.676674 ],
       [-54.535355 , -58.509895 , -61.81874  , -69.491196 , -71.246704 ],
       [-73.44304  , -80.55786  , -82.852974 , -89.520294 , -95.77297  ]],
      dtype=float32)>

#### Perkalian

In [15]:
tf.multiply(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  -4.5347567,    1.7841482,   -5.3580165,    0.9021512,
         -17.865286 ],
       [ -14.3939085,   -1.1359372,  -18.30552  ,    2.200717 ,
          17.168211 ],
       [ -46.39181  ,  -37.395542 ,  -74.008095 ,   49.690166 ,
          15.1963215],
       [ -81.3737   ,   28.916063 ,  -49.9431   , -166.91013  ,
         -17.515917 ],
       [ -32.341805 , -123.07112  ,   12.202995 ,  -46.306206 ,
         119.021454 ]], dtype=float32)>

#### Pembagian

In [16]:
tf.divide(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.1336892 ,  0.19823869, -0.21432066,  0.01841125, -0.147647  ],
       [-0.08517106, -0.00393058, -0.05070781,  0.00416015,  0.02041404],
       [-0.04827452, -0.02731596, -0.04402623,  0.02687408,  0.00687928],
       [-0.02896892,  0.00830683, -0.01342196, -0.03718203, -0.00347469],
       [-0.00606902, -0.01971978,  0.00177137, -0.005846  ,  0.01264974]],
      dtype=float32)>

#### Pangkat

In [17]:
tf.pow(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 5.14100456e+00,  2.10343465e-01, -1.41309130e+00,
         5.90566799e-07, -2.07391113e+02],
       [-3.75889421e+00, -1.05533964e-20, -4.92878944e-01,
         3.62439816e-24,  2.49737838e-07],
       [-2.67589188e+05, -1.48207474e+00, -3.28329052e+10,
         5.01748627e+02,  8.97654211e-24],
       [-7.39666586e+09,  5.33263850e-19, -5.03368028e-06,
        -3.62516853e+26, -0.00000000e+00],
       [-1.54961001e-26, -1.62104830e+15,  0.00000000e+00,
        -5.57412320e-26,  4.15709728e+08]], dtype=float32)>

# Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [27]:
print("Nilai Maksimal Variabel random_tensor", tf.argmax(random_tensor))

Nilai Maksimal Variabel random_tensor tf.Tensor([4 0 4 2 4], shape=(5,), dtype=int64)


In [26]:
print("Nilai Minimal Variabel random_tensor", tf.argmin(random_tensor))

Nilai Minimal Variabel random_tensor tf.Tensor([0 4 2 3 0], shape=(5,), dtype=int64)


# Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [30]:
print("Penggabungan Berdasarkan Kolom")
concatenation_col = tf.concat([random_tensor,prime_tensor],axis=0)
concatenation_col

Penggabungan Berdasarkan Kolom


<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-2.2673783e+00,  5.9471607e-01, -1.0716033e+00,  1.2887874e-01,
        -1.6241169e+00],
       [-1.1072237e+00, -6.6819839e-02, -9.6344835e-01,  9.5683344e-02,
         5.9200728e-01],
       [-1.4965100e+00, -1.0106903e+00, -1.8050754e+00,  1.1555853e+00,
         3.2332599e-01],
       [-1.5353529e+00,  4.9010277e-01, -8.1873935e-01, -2.4911959e+00,
        -2.4670306e-01],
       [-4.4303843e-01, -1.5578623e+00,  1.4702404e-01, -5.2029443e-01,
         1.2270253e+00],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

In [31]:
print("Penggabungan Berdasarkan Baris")
concatenation_row = tf.concat([random_tensor,prime_tensor],axis=1)
concatenation_row

Penggabungan Berdasarkan Baris


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-2.2673783e+00,  5.9471607e-01, -1.0716033e+00,  1.2887874e-01,
        -1.6241169e+00,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [-1.1072237e+00, -6.6819839e-02, -9.6344835e-01,  9.5683344e-02,
         5.9200728e-01,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [-1.4965100e+00, -1.0106903e+00, -1.8050754e+00,  1.1555853e+00,
         3.2332599e-01,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-1.5353529e+00,  4.9010277e-01, -8.1873935e-01, -2.4911959e+00,
        -2.4670306e-01,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         6.7000000e+01,  7.1000000e+01],
       [-4.4303843e-01, -1.5578623e+00,  1.4702404e-01, -5.2029443e-01,
         1.2270253e+00,  7.3000000e+01,  7.9000000e+01,  8.3000000e+01,
         8.9000000e+01,  9.7000000e+01]], dtype=float32)>

# Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [32]:
print("Hasil Sorting random_tensor Secara Descending")
print(tf.sort(random_tensor,direction="DESCENDING"))
print("\n")
print("Hasil Sorting prime_tensor Secara Descending")
print(tf.sort(prime_tensor,direction="DESCENDING"))

Hasil Sorting random_tensor Secara Descending
tf.Tensor(
[[ 0.5947161   0.12887874 -1.0716033  -1.6241169  -2.2673783 ]
 [ 0.5920073   0.09568334 -0.06681984 -0.96344835 -1.1072237 ]
 [ 1.1555853   0.323326   -1.0106903  -1.49651    -1.8050754 ]
 [ 0.49010277 -0.24670306 -0.81873935 -1.535353   -2.491196  ]
 [ 1.2270253   0.14702404 -0.44303843 -0.5202944  -1.5578623 ]], shape=(5, 5), dtype=float32)


Hasil Sorting prime_tensor Secara Descending
tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
